version: '2'

services:

  istex-dl-rp:
    container_name: istex-dl-rp
    image: nginx:1.11.4
    links:
      - istex-dl-www
    volumes:
      - ./logs/:/var/log/nginx
      - ./ngnix/debug.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 45445:80

  istex-dl-www:
    container_name: istex-dl-www
    image: node:6.9.1
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    environment:
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
    ports:
      - 8080:8080
      - 3123:3123
    command: npm run dev
